albumsDirectory: '/home/jdbernard/temp/dkb-site/album-root'
imageFileExtensions: ['png', 'jpg', 'svg', 'jpeg', 'gif', 'tiff']
version:
    minor: 0
    major: 1
title: >
    David K. Bernard - Nature Photogrphs ...
    Wildflowers, Wildlife, Trees, Fungi, Insects, Spiders
    (C) 2008-2016
description: >
    Amateur nature photos of wildlife, wildflowers, trees, fungi, insects, and
    spiders by David K. Bernard, (c) 2004-2016. The primary focus is Austin,
    Texas, with most photos taken at or near the Bernards’ home. There are also
    several galleries of other locations. To see all the galleries, scroll down
    the home page, select from the categories at left, or select from the pages
    at top.
